# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'demoIos' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for demoIos
  pod 'Firebase/Core', '~> 6.3.0'

  target 'demoIos-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'demoIosTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'demoIos-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for demoIos-tvOS

end
